[package]
name = "rustynet"
version = "0.1.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"

[dependencies]
gtk = {git = 'https://github.com/gtk-rs/gtk'}
glib = {git = 'https://github.com/gtk-rs/glib'}
